#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RelativeLayout_App.Resource", IsApplication=true)]

namespace RelativeLayout_App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int Black = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int Blue = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorAccent = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimary = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int colorPrimaryDark = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int Green = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int ic_launcher_background = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int Indigo = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int Orange = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int Red = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int Violet = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int White = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int Yellow = 2130771980;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int challenge1_button = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int challenge2_button = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int challenge3_button = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int linearLayout1 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int relativeLayout1 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int textView1 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int textView2 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int textView3 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int textView4 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int textView5 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int textView6 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int textView7 = 2130837515;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Challenge1_Layout = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int Challenge2_Layout = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Challenge3_Layout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int ic_launcher = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ic_launcher_foreground = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ic_launcher_round = 2130968578;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int action_settings = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int blue = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int green = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int indigo = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int orange = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int red = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int violet = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int yellow = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
